#pragma once
#include <cmath>

const int WINDOW_WIDTH = 767;
const int WINDOW_HEIGHT = 639;

const float PI = std::acos(-1.0);

const int START_BUTTON_WIDTH = 54;
const int START_BUTTON_HEIGHT = 20;

const int PLAYER_START_POSITION_X = 300;
const int PLAYER_START_POSITION_Y = 300;
const int PLAYER_WIDTH = 16;
const int PLAYER_HEIGHT = 32;
const int PLAYER_SPEED = 100;

const int BACKGROUND_MENU_WIDTH = 62;
const int BACKGROUND_MENU_HEIGHT = 46;

// Inventory

const int INVENTORY_WIDTH = 80;
const int INVENTORY_HEIGHT = 102;

const int INVENTORY_POSITION_X = WINDOW_WIDTH / 2 - INVENTORY_WIDTH * 2.5;
const int INVENTORY_POSITION_Y = WINDOW_HEIGHT / 2 - INVENTORY_HEIGHT * 2;

const int INVENTORY_CELLS_POSITION_START_X = INVENTORY_POSITION_X + 60;
const int INVENTORY_CELLS_POSITION_START_Y = INVENTORY_POSITION_Y + 60;

const int INVENTORY_CELLS_PER_ROW = 4;
const int INVENTORY_CELLS_LIMIT = 13;

const int INVENTORY_BUTTON_CLOSE_WIDTH = 32;
const int INVENTORY_BUTTON_CLOSE_HEIGHT = 13;

// Pokemons

const int BULBASOUR_POSITION_X = PLAYER_START_POSITION_X + 100;
const int BULBASOUR_POSITION_Y = PLAYER_START_POSITION_Y;
const int POKEMON_INVENTORY_WIDTH = 36;
const int POKEMON_INVENTORY_HEIGHT = 33;

// Catching

const int CATCHING_LOCATION_WIDTH = 383;
const int CATCHING_LOCATION_HEIGHT = 640;

const int ARROW_WIDTH = 57;
const int ARROW_HEIGHT = 162;

const int ARROW_POS_X = WINDOW_WIDTH / 2;
const int ARROW_POS_Y = WINDOW_HEIGHT - 70;

const int ARROW_SPEED = 2;

const int ARROW_POKEBALL_GAP = 30;

const float ARROW_MAX_ANGLE = PI / 6 * 2;
const float ARROW_MIN_ANGLE = - PI / 6 * 2;

const int POKEBALL_WIDTH = 13;
const int POKEBALL_HEIGHT = 12;

const int POKEBALL_SPEED = 500;

const int POKEBALL_POS_X = ARROW_POS_X;
const int POKEBALL_POS_Y = ARROW_POS_Y + POKEBALL_HEIGHT / 2;

const float ARROW_RADIUS = ARROW_POKEBALL_GAP + POKEBALL_HEIGHT / 2;

// Items Chest

const int ITEM_SIDE = 30;

const int CHEST_INTERFACE_TEXTURE_WIDTH = 230;
const int CHEST_INTERFACE_TEXTURE_HEIGHT = 79;

const int CHEST_INTERFACE_WIDTH = CHEST_INTERFACE_TEXTURE_WIDTH * 2;
const int CHEST_INTERFACE_HEIGHT = CHEST_INTERFACE_TEXTURE_HEIGHT * 2;

const int CHEST_INTERFACE_X = WINDOW_WIDTH / 2 - CHEST_INTERFACE_WIDTH / 2;
const int CHEST_INTERFACE_Y = WINDOW_HEIGHT / 2 - CHEST_INTERFACE_HEIGHT / 2;

const int MAX_ITEMS_PER_ROW = 9;

const int CHEST_WIDTH = 24;
const int CHEST_HEIGHT = 23;

const int CHEST_INTERFACE_BUTTON_CLOSE_X = CHEST_INTERFACE_X;
const int CHEST_INTERFACE_BUTTON_CLOSE_Y = CHEST_INTERFACE_HEIGHT + CHEST_INTERFACE_Y;

const int CHEST_INTERFACE_BUTTON_WIDTH = INVENTORY_BUTTON_CLOSE_WIDTH * 4;
const int CHEST_INTERFACE_BUTTON_HEIGHT = INVENTORY_BUTTON_CLOSE_HEIGHT *4;

const int CHEST_INTERFACE_BUTTON_GET_X = CHEST_INTERFACE_X + CHEST_INTERFACE_WIDTH - CHEST_INTERFACE_BUTTON_WIDTH;
const int CHEST_INTERFACE_BUTTON_GET_Y = CHEST_INTERFACE_HEIGHT + CHEST_INTERFACE_Y;



